### ISSUE TITLE
Please remove hardcoded admin email.

### ISSUE THREAD

**Issue by andwah** [Starcounter/UserAdmin#102]
Hardcoded admin email

https://github.com/StarcounterApps/UserAdmin/blob/refactor-without-simplified/src/UserAdmin/Helpers/SystemUserAdmin.cs#L122

**Comment by Mihaiii** [comment]
Yes, the change was made in this commit: https://github.com/StarcounterApps/UserAdmin/commit/b5d0187fcd278c8be07c2479846dc542b165c217#diff-74a05b0cbb53d32e725d5fc9a7f756c3R122 .

The code was taken from SignIn app when it was decided to have the creation of the default admin user in UserAdmin instead of SignIn .

I pushed the change with the value from SignIn app, `master` branch: https://github.com/StarcounterApps/SignIn/blob/master/src/SignIn/Models/SystemAdminUser.cs#L18

Indeed, my email address shouldn't be in the code.

Regarding the fact that is a hardcoded value (no matter what's the hardcoded email address), this will be discussed in apps team's next meeting to see if it's worth putting an email field in the form or not for the first admin user.

Thank you for reporting!
